language: node_js
node_js:
  - 10
  - 12
  - 13
  - 14
  - 15

env:
  global:
    - API_PORT=3000
    - DATASOURCE_lOCATION=/home/travis/build/00F100/covid-chart/api/infra/data/database.sqlite
    - DATASOURCE_lOCATION_ORIGINAL=/home/travis/build/00F100/covid-chart/api/infra/data/database.sqlite
    - VIEW_INDEX=/home/travis/build/00F100/covid-chart/api/src/public
    - LOGGER_LEVEL=info
    - LOGGER_TYPE=file
    - LOGGER_FILE=/var/log/covidlast-api-extractor.log
    - DIR_NAME=/home/travis/build/00F100/covid-chart/api/src
    - NODE_ENV=development
    - EXTRACT_TARGET_HOSTNAME=https://www.worldometers.info
    - EXTRACT_TARGET_METHOD=GET
    - EXTRACT_TARGET_PATH=/coronavirus/country/%s
    - HELPER_FILTER_CASES=true
    - HELPER_FILTER_DEATHS=true
    - HELPER_FILTER_ACTIVE=false
    - VUE_APP_API_SCHEMA=https
    - VUE_APP_API_HOST=api.covidlast.com
    - VUE_APP_API_PORT=
    - VUE_GOOGLE_ANALYTICS_TAG=

jobs:
  include:
    - stage: API
      script: cd api && npm install && npm run build
    - stage: Extract
      script: cd api && npm install && npm run build && node dist/bootstrap/handler.js extract 1
    - stage: Validate
      script: cd api && npm install && npm run build && node dist/bootstrap/handler.js test-datasource
    - stage: Frontend
      script: cd frontend && npm install && npm run build